let AGGREEMENT_NOTICE_ID = "AGGREEMENT_NOTICE_ID"
let VERSION_NOTICE_ID = "VERSION_NOTICE_ID"
// 定义常量
let FIRST_PRODUCT_NOTICE_ID = "FIRST_PRODUCT_NOTICE"
let JOIN_SUCCESS_NOTICE_ID = "JOIN_SUCCESS_NOTICE"

 let BASR_SERVE_URL = "https://api.apptune.cn"
//let BASR_SERVE_URL: String = "http://192.168.3.9:8000"

let IMAGE_SERVER_URL = "\(BASR_SERVE_URL)/"
